- name: add ssh key for didin
  authorized_key:
    user: didin
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJweeF1POdBnpbSYYnRrmtpHVb2EHhdO40PLZWBadpE+ ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
